version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smile_classifier_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: smile_db
      TZ: Asia/Dhaka
    ports:
      - "5433:5432"  # <-- Changed host port from 5432 to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: smile_classifier_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/smile_db
      TZ: Asia/Dhaka
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: